# Generated by Django 4.0.4 on 2022-05-03 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubcard',
            name='discount',
        ),
    ]
