# Generated by Django 4.0.4 on 2022-05-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='amount_of_row',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='room',
            name='amount_of_seat',
            field=models.PositiveSmallIntegerField(default=15),
        ),
    ]
